name: Conflicts Checker
description: Check for conflicts in the PR for release please in mono-repo
inputs:
  repo:
    description: 'The repository to check for conflicts'
    required: true
  token:
    description: 'The token to use for the repository'
    required: true
outputs:
  need_rebase:
    value: ${{ steps.needs_rebase.outputs.need_rebase }}
    description: 'Whether the PR needs a rebase'
runs:
  using: 'composite'
  steps:
    - name: Needs rebase
      shell: bash
      id: needs_rebase
      env:
        REPO: ${{ inputs.repo }}
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        set -euo pipefail
        pending_prs=$(gh pr list --repo "$REPO" --label "autorelease: pending" --state open --json number --jq '.[].number')
        need_rebase=""

        if [[ -n "$pending_prs" ]]; then
            for pr_num in $pending_prs; do
                echo "Checking pr: $pr_num"
                mergeable=$(gh pr view --repo "$REPO" "$pr_num" --json mergeable --jq '.mergeable')
                echo "mergeable status: $mergeable"
                if [[ "$mergeable" != "MERGEABLE" ]]; then
                    echo "pr: $pr_num is not MERGEABLE."
                    echo "removing 'autorelease: pending' label from pr: $pr_num"
                    gh pr edit --repo "$REPO" "$pr_num" --remove-label "autorelease: pending"
                    need_rebase=true
                fi
            done
        else
            echo "No pending PRs found."
            exit 0
        fi

        if [[ -n "$need_rebase" ]]; then
            echo "not MERGEABLE status PRs found."
            echo "need_rebase=$need_rebase"
            echo "need_rebase=$need_rebase" >> "$GITHUB_OUTPUT"
        else
            echo "All pending PRs are MERGEABLE."
        fi
